const { app, BrowserWindow } = require("electron");
const path = require("path");
const { spawn } = require("child_process");

let pythonProcess = null;

function startPythonBackend() {
  // Point to the executable generated by PyInstaller
  const script = path.join(__dirname, "bin", "main.exe");
  pythonProcess = spawn(script, [], { detached: true });
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
  });

  // Construct the absolute path correctly
  const indexPath = path.join(
    __dirname,
    "..",
    "src",
    "nexus-rag-ui",
    "dist",
    "index.html",
  );
  console.log("Attempting to load index.html from:", indexPath);

  win.loadFile(indexPath).catch((err) => {
    console.error("Failed to load index.html:", err);
  });
}

app.whenReady().then(() => {
  startPythonBackend();
  createWindow();
});

app.on("window-all-closed", () => {
  if (pythonProcess) pythonProcess.kill();
  app.quit();
});
